### ISSUE TITLE
Persistent Scene Perspective

### ISSUE THREAD

**Issue by noam2000** [purifetchi/Fern#2]
Currently, changing the size of the scene window squishes the view, instead of keeping the perspective consistent.
![image (13)](https://github.com/purifetchi/Fern/assets/72533507/61ca239c-d382-4fef-b408-ba88a5f8167d)

**Comment by purifetchi** [comment]
Fixed
![image](https://github.com/purifetchi/Fern/assets/9293619/5765eac4-7d47-4f0d-b3c5-21025ebc6f51)
